use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let books_dir = Path::new(&manifest_dir).join("assets/books");

    if !books_dir.exists() {
        println!("cargo:warning=assets/books/ directory not found, skipping book generation");
        return;
    }

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("books_generated.rs");

    let mut entries: Vec<(u32, String)> = Vec::new();

    for entry in fs::read_dir(&books_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("json") {
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                if let Some(year_str) = stem.split('_').next() {
                    if let Ok(year) = year_str.parse::<u32>() {
                        entries.push((year, stem.to_string()));
                    }
                }
            }
        }
    }

    entries.sort_by(|a, b| b.0.cmp(&a.0));

    let mut code = String::from("// Generated by build.rs - do not edit\n");
    code.push_str(
        "pub fn get_all_books() -> Vec<YearBooks> {\n    let mut years: Vec<YearBooks> = Vec::new();\n"
    );

    for (year, stem) in &entries {
        let year = *year;
        code.push_str(&format!(
            "    years.push(YearBooks {{\n  year: {year},\n  books: serde_json::from_str(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/books/{stem}.json\"))).unwrap_or_default(),\n    }});\n",
        ));
    }

    code.push_str("    years\n}\n");

    fs::write(&dest_path, code).unwrap();

    println!("cargo:rerun-if-changed=assets/books/");
}
